# Generated by Django 4.0.5 on 2022-06-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('authorized', models.CharField(max_length=64)),
                ('org_image', models.ImageField(blank=True, null=True, upload_to='organization')),
                ('address', models.TextField()),
                ('org_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=64)),
                ('activity_image', models.ImageField(blank=True, null=True, upload_to='activity')),
                ('active', models.BooleanField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('org_name', models.ManyToManyField(to='posts.organization')),
            ],
            options={
                'ordering': ['-starttime'],
            },
        ),
    ]
